import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {Roboto} from "next/font/google"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Snitch UI Demo",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight:["100","300","400","500","700","900"],
  variable:"--font-roboto",
  subsets:["latin"]
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          className={cn(
            "min-h-full",
            "font-roboto",
            "bg-background antialiased"
            
          )}
        >
          <Navbar/>
          {children}
          <Footer/>
        </body>
      </html>
    
  );
}
